# Generated by Django 3.1 on 2020-08-24 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200824_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='getrooms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='getrooms',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='getrooms',
            name='hotel_room_facilities',
            field=models.CharField(max_length=255),
        ),
    ]
